# Production RAG Masterclass

## Notebook 01 — Embedding Basics

**Module:** Embeddings

**Status:** In Progress

---

## Objective

Understand how embedding models convert text into fixed-length semantic vectors and how semantic similarity can be measured.

---

## Topics Covered

- Loading an embedding model
- Generating sentence embeddings
- Inspecting embedding vectors
- Fixed-length representations
- Comparing embeddings
- Cosine similarity

---

## Hypothesis

Before running any experiments:

- Similar sentences should produce similar embeddings.
- Unrelated sentences should produce dissimilar embeddings.
- Every embedding produced by the same model should have the same number of dimensions.
- Individual values inside an embedding are not directly interpretable.

## Step 1 — Import Libraries

In [2]:
import numpy as np
from sentence_transformers import SentenceTransformer

## Step 2 — Load the Embedding Model

In [3]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

## Step 3 — Generate Your First Embedding

In [4]:
sentence = "The doctor examined the patient."

embedding = model.encode(sentence)

## Step 4 — Inspect the Embedding

In [5]:
type(embedding)

numpy.ndarray

In [6]:
embedding.shape

(384,)

In [7]:
embedding[:10]

array([ 0.02981187,  0.11060002, -0.06280765,  0.00388033, -0.07090655,
       -0.05839539,  0.02076475,  0.11135695, -0.004465  , -0.01403826],
      dtype=float32)

In [8]:
sentences = [
    "The doctor examined the patient.",
    "The physician checked the patient.",
    "The banana fell from the tree."
]

embeddings = model.encode(sentences)

embeddings.shape

(3, 384)

In [10]:
embeddings.shape

(3, 384)

In [12]:
embeddings[0].shape

(384,)

In [13]:
embeddings[1].shape

(384,)

In [14]:
embeddings[:, 0].shape

(3,)

In [16]:
embeddings[0][:10].shape

(10,)

## Step 5 — Compare Similar Sentences

In [17]:
from sentence_transformers import util

In [21]:
sentence1 = "The doctor examined the patient."
sentence2 = "The physician checked the patient."
sentence3 = "The banana fell from the tree."

embedding1 = model.encode(sentence1)
embedding2 = model.encode(sentence2)
embedding3 = model.encode(sentence3)

similarity_12 = util.cos_sim(embedding1, embedding2)
similarity_13 = util.cos_sim(embedding1, embedding3)

print(similarity_12)
print(similarity_13)

tensor([[0.8526]])
tensor([[0.0540]])


In [23]:
similarity_11 = util.cos_sim(embedding1, embedding1)
print(similarity_11)

tensor([[1.]])


In [27]:
sentence3 = "The surgeon performed the operation."
embedding3 = model.encode(sentence3)
similarity_13 = util.cos_sim(embedding1, embedding3)
print(similarity_13.item())

0.5738577246665955


In [28]:
sentence3 = "The mechanic repaired the engine."
embedding3 = model.encode(sentence3)
similarity_13 = util.cos_sim(embedding1, embedding3)
print(similarity_13.item())

0.3034622073173523


In [29]:
sentence3 = "The patient was examined by the doctor."
embedding3 = model.encode(sentence3)
similarity_13 = util.cos_sim(embedding1, embedding3)
print(similarity_13.item())

0.9769289493560791


In [30]:
sentence3 = "The patient examined the doctor."
embedding3 = model.encode(sentence3)
similarity_13 = util.cos_sim(embedding1, embedding3)
print(similarity_13.item())

0.992119312286377


In [32]:
sentence1 = "Refunds are allowed within 30 days."
sentence2 = "Refunds are not allowed within 30 days."

embedding1 = model.encode(sentence1)
embedding2 = model.encode(sentence2)

similarity_12 = util.cos_sim(embedding1, embedding2)
print(similarity_12.item()) 

0.9604220986366272
